### ISSUE TITLE
MSI package

### ISSUE THREAD

**Issue by bifacil** [kurai021/MDWriter#4]
Exists a MSI package to install it on Windows?

I know I could clone, install dependencies, compile... But I am asking for an easier way to use your software without all that hassle...

**Comment by kurai021** [comment]
I just did builds for GNU/Linux and Windows for testing, I could make a release of this repo.

**Comment by bifacil** [comment]
It would be great.

**Comment by kurai021** [comment]
check this release, include a zip with .exe https://github.com/kurai021/MDWriter/releases/tag/v16.03.3

**Comment by bifacil** [comment]
Thanks!
